name: grade
version: 1.0
main: fr.sicsou.grade.RolePlugin
api-version: 1.21
author: SicSou
description: Gestion simple des grades joueurs.

commands:
  setgrade:
    description: Définit le grade d'un joueur.
    usage: /setgrade <joueur> <grade>
    permission: grade.set

permissions:
  grade.set:
    description: Permet de définir le grade d'un joueur.
    default: op
